service: product-service
# app and org for use with dashboard.serverless.com
app: dah-order
org: dahorder

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-southeast-1'}
  profile: dahorder2
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.productTable}
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.productTable}/index/id

  environment:
    DYNAMODB_PRODUCT_TABLE: ${self:custom.dynamodb.productTable}
    JWT_SECRET: ${param:JWT_SECRET}
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

functions:
  updateProduct:
    handler: src/functions/updateProduct.handler
    events:
      - http:
         path: /product
         method: put
         cors: true
         authorizer: authorizer
  authorizer:
    handler: src/functions/authorizer.validate
  listProducts:
    handler: src/functions/listProducts.handler
    events:
      - http:
          path: /products
          method: get
          cors: true
  addProduct:
    handler: src/functions/addProduct.handler
    events:
      - http:
          path: /product
          method: post
          cors: true
          authorizer: authorizer
  getProduct:
    handler: src/functions/getProduct.handler
    events:
      - http:
          path: /product
          method: get
          cors: true

resources:
  Resources:
    shopTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.productTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha

custom:
  dynamodb:
    productTable: product-${self:provider.stage}-${self:provider.region}
  serverless-mocha-plugin:
    testTemplate: ../templates/test-template.ejs
    functionTemplate: ../templates/function-template.ejs
