service: user-service
# app and org for use with dashboard.serverless.com
app: dah-order
org: dahorder

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: dahorder2
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-southeast-1'}
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
        - "sns:Publish"
        - "sns:Subscribe"
        - "sns:ConfirmSubscription"
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.userTable}
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.userTable}/index/pk
        - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:userRegistered-${self:provider.stage}
  
  environment:
    DYNAMODB_USER_TABLE: ${self:custom.dynamodb.userTable}
    JWT_SECRET: ${param:JWT_SECRET}
    WABLAS_TOKEN: ${param:WABLAS_TOKEN}
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

functions:
  requestReset:
    handler: src/functions/requestReset.handler
    events:
      - http:
          path: /user/reset
          method: get
          cors: true
  resetPassword:
    handler: src/functions/resetPassword.handler
    events:
      - http:
          path: /user/password
          method: put
          cors: true
  updateUser:
    handler: src/functions/updateUser.handler
    events:
      - http:
          path: /user
          method: put
          cors: true
          authorizer: validate
  getUser:
    handler: src/functions/getUser.handler
    events:
      - http:
          path: /user
          method: get
          cors: true
  validate:
    handler: src/functions/validate.validate
  login:
    handler: src/functions/login.login
    events:
      - http:
          path: /user/login
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(src/schema/login_request.json)}
  createUser:
    handler: src/functions/createUser.createUser
    events:
      - http:
          path: /user
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(src/schema/create_user_request.json)}

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.userTable}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    userRegisteredTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: userRegistered-${self:provider.stage}
    userRegisteredSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: EMAIL
        Endpoint: azrin.zuhdi@gmail.com
        TopicArn: {"Ref": "userRegisteredTopic"}

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha
custom:
  dynamodb:
    userTable: user-${self:provider.stage}-${self:provider.region}
  serverless-mocha-plugin:
    testTemplate: ../templates/test-template.ejs
    functionTemplate: ../templates/function-template.ejs