org: dahorder
app: dah-order
name: admin
component: website

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
  region: ap-southeast-1
  bucketName: admin.dahorder.my
  domain: admin.dahorder.my