service: shop-service
# app and org for use with dashboard.serverless.com
app: dah-order
org: dahorder

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  profile: dahorder
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.shopTable}
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.shopTable}/index/pk

  environment:
    DYNAMODB_SHOP_TABLE: ${self:custom.dynamodb.shopTable}
    JWT_SECRET: ${param:JWT_SECRET}
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

functions:
  getShop:
    handler: src/functions/getShop.handler
    events:
      - http:
          path: /shop
          method: get
          cors: true
  authorizer:
    handler: src/functions/authorizer.validate
  myShops:
    handler: src/functions/myShops.handler
    events:
      - http:
          path: /myshops
          method: get
          cors: true
          authorizer: authorizer
  listShops:
    handler: src/functions/listShops.handler
    events:
      - http:
          path: /listshops
          method: get
          cors: true
  addShop:
    handler: src/functions/addShop.handler
    events:
      - http:
          path: /shop
          method: post
          cors: true
          authorizer: authorizer

resources:
  Resources:
    shopTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.shopTable}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha

custom:
  dynamodb:
    shopTable: shop-${self:provider.stage}-${self:provider.region}
  serverless-mocha-plugin:
    testTemplate: ../templates/test-template.ejs
    functionTemplate: ../templates/function-template.ejs