service: shop-service
# app and org for use with dashboard.serverless.com
app: dah-order
org: sterling000

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.shopTable}
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.dynamodb.shopTable}/index/pk

  environment:
    DYNAMODB_SHOP_TABLE: ${self:custom.dynamodb.shopTable}
    JWT_SECRET: ${param:JWT_SECRET}

functions:
  addShop:
    handler: src/functions/addShop.handler
    events:
      - http:
          path: /shop
          method: post
          cors: true

resources:
  Resources:
    shopTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.dynamodb.shopTable}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-pseudo-parameters
  - serverless-mocha

custom:
  dynamodb:
    shopTable: shop-${self:provider.stage}
  serverless-mocha-plugin:
    testTemplate: ../templates/test-template.ejs
    functionTemplate: ../templates/function-template.ejs