org: dahorder
app: dah-order
name: website
component: website

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
  region: ap-southeast-1
  bucketName: dahorder.my
  domain: dahorder.my